modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="got"
version="1.0.0"
displayName="got"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.got]]
    modId="neoforge"
    type="required"
    versionRange="[21.3.95]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.got]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.3]"
    ordering="AFTER"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration